import { User } from '@/types/user';

export const mockUsers: User[] = [
  {
    id: 'user-001',
    name: 'Toufique Joarder',
    nameEn: 'Toufique Joarder',
    nameBn: 'তৌফিক জোয়ার্দার',
    email: 'toufique.joarder@rnpl.com',
    role: 'Admin',
    designationEn: 'Managing Director',
    designationBn: 'ব্যবস্থাপনা পরিচালক',
    officeEn: 'Administration',
    officeBn: 'প্রশাসন',
    avatarId: 1,
    status: 'Active',
    dateJoined: '2023-01-15',
  },
  {
    id: 'user-002',
    name: 'Rashida Begum',
    nameEn: 'Rashida Begum',
    nameBn: 'রাশিদা বেগম',
    email: 'rashida.begum@rnpl.com',
    role: 'Author',
    designationEn: 'Senior Executive',
    designationBn: 'সিনিয়র এক্সিকিউটিভ',
    officeEn: 'Finance',
    officeBn: 'অর্থ বিভাগ',
    avatarId: 3,
    status: 'Active',
    dateJoined: '2023-06-20',
  },
  {
    id: 'user-003',
    name: 'Karim Uddin',
    nameEn: 'Karim Uddin',
    nameBn: 'করিম উদ্দিন',
    email: 'karim.uddin@rnpl.com',
    role: 'Reviewer',
    designationEn: 'Manager',
    designationBn: 'ব্যবস্থাপক',
    officeEn: 'Human Resources',
    officeBn: 'মানবসম্পদ বিভাগ',
    avatarId: 2,
    status: 'Active',
    dateJoined: '2023-03-10',
  },
  {
    id: 'user-004',
    name: 'Fatima Ahmed',
    nameEn: 'Fatima Ahmed',
    nameBn: 'ফাতিমা আহমেদ',
    email: 'fatima.ahmed@rnpl.com',
    role: 'Approver',
    designationEn: 'Director',
    designationBn: 'পরিচালক',
    officeEn: 'Operations',
    officeBn: 'অপারেশনস বিভাগ',
    avatarId: 4,
    status: 'Active',
    dateJoined: '2023-02-05',
  },
  {
    id: 'user-005',
    name: 'Mohammad Hasan',
    nameEn: 'Mohammad Hasan',
    nameBn: 'মোহাম্মদ হাসান',
    email: 'hasan.mohammad@rnpl.com',
    role: 'Author',
    designationEn: 'IT Specialist',
    designationBn: 'আইটি বিশেষজ্ঞ',
    officeEn: 'Information Technology',
    officeBn: 'তথ্য প্রযুক্তি বিভাগ',
    avatarId: 6,
    status: 'Active',
    dateJoined: '2024-01-10',
  },
  {
    id: 'user-006',
    name: 'Nusrat Jahan',
    nameEn: 'Nusrat Jahan',
    nameBn: 'নুসরাত জাহান',
    email: 'nusrat.jahan@rnpl.com',
    role: 'Reviewer',
    designationEn: 'Assistant Manager',
    designationBn: 'সহকারী ব্যবস্থাপক',
    officeEn: 'Marketing',
    officeBn: 'বিপণন বিভাগ',
    avatarId: 5,
    status: 'Active',
    dateJoined: '2023-11-15',
  },
  {
    id: 'user-007',
    name: 'Sharmin Akter',
    nameEn: 'Sharmin Akter',
    nameBn: 'শারমিন আক্তার',
    email: 'sharmin.akter@rnpl.com',
    role: 'Author',
    designationEn: 'HR Executive',
    designationBn: 'মানবসম্পদ এক্সিকিউটিভ',
    officeEn: 'Human Resources',
    officeBn: 'মানবসম্পদ বিভাগ',
    avatarId: 10,
    status: 'Active',
    dateJoined: '2024-02-01',
  },
  {
    id: 'user-008',
    name: 'Abul Kashem',
    nameEn: 'Abul Kashem',
    nameBn: 'আবুল কাশেম',
    email: 'kashem.abul@rnpl.com',
    role: 'Approver',
    designationEn: 'Chief Financial Officer',
    designationBn: 'প্রধান অর্থ কর্মকর্তা',
    officeEn: 'Finance',
    officeBn: 'অর্থ বিভাগ',
    avatarId: 7,
    status: 'Active',
    dateJoined: '2023-01-20',
  },
  {
    id: 'user-009',
    name: 'Sultana Razia',
    nameEn: 'Sultana Razia',
    nameBn: 'সুলতানা রাজিয়া',
    email: 'razia.sultana@rnpl.com',
    role: 'Reviewer',
    designationEn: 'Procurement Officer',
    designationBn: 'ক্রয় কর্মকর্তা',
    officeEn: 'Administration',
    officeBn: 'প্রশাসন',
    avatarId: 11,
    status: 'Inactive',
    dateJoined: '2023-05-12',
  },
  {
    id: 'user-010',
    name: 'Jasim Uddin',
    nameEn: 'Jasim Uddin',
    nameBn: 'জসিম উদ্দিন',
    email: 'jasim.uddin@rnpl.com',
    role: 'Author',
    designationEn: 'Supply Chain Analyst',
    designationBn: 'সাপ্লাই চেইন বিশ্লেষক',
    officeEn: 'Operations',
    officeBn: 'অপারেশনস বিভাগ',
    avatarId: 8,
    status: 'Active',
    dateJoined: '2024-03-01',
  },
];

export const getMockUserById = (id: string) => mockUsers.find(u => u.id === id);
export const getMockUserByName = (name: string) => mockUsers.find(u => u.nameEn === name || u.nameBn === name || u.name === name);

